using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace WhiteboardCSharp
{
    public class Whiteboard
    {
        public void ShowWhiteboard()
        {
            //Challenge1 challenge1 = new Challenge1();
            //Challenge2 challenge2 = new Challenge2();
            //Challenge3 challenge3 = new Challenge3();
            //Challenge4 challenge4 = new Challenge4();
            //Challenge5 challenge5 = new Challenge5();
            //Challenge6 challenge6 = new Challenge6();
            //Challenge7 challenge7 = new Challenge7();
            //Challenge8 challenge8 = new Challenge8();
            //Challenge9 challenge9 = new Challenge9();
            //Challenge10 challenge10 = new Challenge10();
            //Challenge11 challenge11 = new Challenge11();
            //Challenge12 challenge12 = new Challenge12();
            //Challenge13 challenge13 = new Challenge13();
            //Challenge14 challenge14 = new Challenge14();
            //Challenge15 challenge15 = new Challenge15();
            //Challenge16 challenge16 = new Challenge16();
            //Challenge17 challenge17 = new Challenge17();
            //Challenge18 challenge18 = new Challenge18();
            //Challenge19 challenge19 = new Challenge19();
            //Challenge20 challenge20 = new Challenge20();
            //Challenge21 challenge21 = new Challenge21();
            //Challenge22 challenge22 = new Challenge22();
            //Challenge23 challenge23 = new Challenge23();
            //Challenge24 challenge24 = new Challenge24(); 
            //Challenge25 challenge25 = new Challenge25();
            //Challenge26 challenge26 = new Challenge26();
            //Challenge27 challenge27 = new Challenge27();
            //Challenge28 challenge28 = new Challenge28();
            //Challenge29 challenge29 = new Challenge29();
            //Challenge30 challenge30 = new Challenge30();
            //Challenge31 challenge31 = new Challenge31();
            //Challenge32 challenge32 = new Challenge32();
            //Challenge33 challenge33 = new Challenge33();
            //Challenge34 challenge34 = new Challenge34();
            //Challenge35 challenge35 = new Challenge35();
            //Challenge36 challenge36 = new Challenge36();
            //Challenge37 challenge37 = new Challenge37();
            //Challenge38 challenge38 = new Challenge38();
            //Challenge39 challenge39 = new Challenge39();
            //Challenge40 challenge40 = new Challenge40();
            // Challenge41 challenge41 = new Challenge41();
            //Challenge42 challenge42 = new Challenge42();
            //Challenge43 challenge43 = new Challenge43();
            //Challenge44 challenge44 = new Challenge44();
            //Challenge45 challenge45 = new Challenge45();
            //Challenge46 challenge46 = new Challenge46();
            //Challenge47 challenge47 = new Challenge47();
            //Challenge48 challenge48 = new Challenge48();
            //Challenge49 challenge49 = new Challenge49();
            //Challenge50 challenge50 = new Challenge50();
            //Challenge51 challenge51 = new Challenge51();
            //Challenge52 challenge52 = new Challenge52();
            //Challenge53 challenge53 = new Challenge53();
            //Challenge54 challenge54 = new Challenge54();
            //Challenge55 challenge55 = new Challenge55();
            //Challenge56 challenge56 = new Challenge56();
            Challenge57 challenge57 = new Challenge57();
            
            Console.WriteLine("\n\n       Welcome to Matt's C# Whiteboard!");

            //challenge1.RunChallenge();
            //challenge2.RunChallenge();
            //challenge3.RunChallenge();
            //challenge4.RunChallenge();
            //challenge5.RunChallenge();
            //challenge6.RunChallenge();
            //challenge7.RunChallenge();
            //challenge8.RunChallenge();
            //challenge9.RunChallenge();
            //challenge10.RunChallenge();
            //challenge11.RunChallenge();
            //challenge12.RunChallenge();
            //challenge13.RunChallenge();
            //challenge14.RunChallenge();
            //challenge15.RunChallenge();
            //challenge16.RunChallenge();
            //challenge17.RunChallenge();
            //challenge18.RunChallenge();
            //challenge19.RunChallenge();
            //challenge20.RunChallenge();
            //challenge21.RunChallenge();
            //challenge22.RunChallenge();
            //challenge23.RunChallenge();
            //challenge24.RunChallenge();
            //challenge25.RunChallenge();
            //challenge26.RunChallenge();
            //challenge27.RunChallenge();
            //challenge28.RunChallenge();
            //challenge29.RunChallenge();
            //challenge30.RunChallenge();
            //challenge31.RunChallenge();
            //challenge32.RunChallenge();
            //challenge33.RunChallenge();
            //challenge34.RunChallenge();
            //challenge35.RunChallenge();
            //challenge36.RunChallenge();
            //challenge37.RunChallenge();
            //challenge38.RunChallenge();
            //challenge39.RunChallenge();
            //challenge40.RunChallenge();
            //challenge41.RunChallenge();
            //challenge42.RunChallenge();
            //challenge43.RunChallenge();
            //challenge44.RunChallenge();
            //challenge45.RunChallenge();
            //challenge46.RunChallenge();
            //challenge47.RunChallenge();
            //challenge48.RunChallenge();
            //challenge49.RunChallenge();
            //challenge50.RunChallenge();
            //challenge51.RunChallenge();
            //challenge52.RunChallenge();
            //challenge53.RunChallenge();
            //challenge54.RunChallenge();
            //challenge55.RunChallenge();
            //challenge56.RunChallenge();
            challenge57.RunChallenge();
        }
    }
}
